# Generated by Django 6.1 on 2026-08-14 15:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(help_text='Razón social del proveedor', max_length=255)),
                ('cuit', models.BigIntegerField(help_text='CUIT del proveedor (11 dígitos sin separadores)', unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cuit', message='El CUIT debe tener exactamente 11 dígitos', regex='^\\d{11}$')])),
                ('telefono', models.BigIntegerField(blank=True, help_text='Número de teléfono del proveedor', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
                'indexes': [models.Index(fields=['cuit'], name='compra_prov_cuit_fbe8f9_idx'), models.Index(fields=['razon_social'], name='compra_prov_razon_s_7132db_idx')],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio unitario del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_actual', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en stock')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('proveedor', models.ForeignKey(help_text='Proveedor del producto', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='compra.proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='compra_prod_nombre_0fa11e_idx'), models.Index(fields=['proveedor'], name='compra_prod_proveed_3b7367_idx')],
            },
        ),
    ]
